// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	AuthToken        string
	CityIndex        string
	Parcel           string
	SchemaMigrations string
	User             string
}{
	AuthToken:        "auth_token",
	CityIndex:        "city_index",
	Parcel:           "parcel",
	SchemaMigrations: "schema_migrations",
	User:             "user",
}
